#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Generated by scripts/build-standalone.sh from the ordered files in src/.
# Edit the modules, then regenerate this standalone installer.
# Single-core VPN server installer for a clean supported amd64 VPS.
#
# Default action is read-only:
#   ./install-sing-box-server.sh plan
#   sudo ./install-sing-box-server.sh check
#
# Interactive installation:
#   sudo ./install-sing-box-server.sh install
#
# Management after installation:
#   vpn health
#   vpn add WorkPC
#   vpn show
#   vpn show WorkPC
#   vpn set-target example.com
#   vpn set-fingerprint
#   vpn set-obfs off|salamander
#   vpn update
#   vpn self-update /path/to/new/install-sing-box-server.sh
#
# This script intentionally does not install a web panel, Docker, Xray, UFW,
# fail2ban, or experimental sing-box builds. nginx-light serves only private,
# tokenized, read-only subscription files.

set -Eeuo pipefail
IFS=$'\n\t'
umask 077

readonly SCRIPT_VERSION="1.0.10"
readonly SING_BOX_MIN_VERSION="1.13.0"
readonly SING_BOX_MAX_EXCLUSIVE="1.14.0"
readonly PROJECT_NAME="vpn-setup"
readonly SAGERNET_KEY_URL="https://sing-box.app/gpg.key"
readonly SAGERNET_KEY_FILE="/etc/apt/keyrings/sagernet.asc"
readonly SAGERNET_SOURCE_FILE="/etc/apt/sources.list.d/sagernet.sources"

readonly STATE_DIR="/var/lib/${PROJECT_NAME}"
readonly ROLLBACK_DIR="${STATE_DIR}/rollback"
readonly SECRETS_FILE="${STATE_DIR}/server-secrets.env"
readonly CLIENTS_FILE="${STATE_DIR}/clients.json"
readonly CLIENT_LOCK_FILE="${STATE_DIR}/clients.lock"
readonly SETTINGS_FILE="${STATE_DIR}/settings.json"
readonly INSTALL_COMPLETE_FILE="${STATE_DIR}/install.complete"
readonly RUNTIME_VERSION_FILE="${STATE_DIR}/runtime.version"
readonly INSTALL_LOCK_FILE="${STATE_DIR}/install.lock"
readonly FIREWALL_LOCK_FILE="${STATE_DIR}/firewall.lock"
readonly PACKAGE_CACHE_DIR="${STATE_DIR}/packages"
readonly INSTALLER_BACKUP_DIR="${STATE_DIR}/installer-backups"
readonly INITIAL_CLIENT_NAME="default"
readonly DEFAULT_CLIENT_FINGERPRINT="chrome"
readonly DEFAULT_HY2_OBFS_MODE="off"
readonly -a SUPPORTED_CLIENT_FINGERPRINTS=(
  chrome firefox safari ios android edge 360 qq random
)
readonly -a SUPPORTED_HY2_OBFS_MODES=(off salamander)
readonly SUBSCRIPTION_PORT="8443"
readonly SUBSCRIPTION_ROOT="/var/www/vpn-subscriptions"
readonly NGINX_SITE="/etc/nginx/sites-available/vpn-subscription"
readonly NGINX_SITE_ENABLED="/etc/nginx/sites-enabled/vpn-subscription"
readonly UDP_BUFFER_MAX="7340032"
readonly CONFIG_DIR="/etc/sing-box"
readonly CONFIG_FILE="${CONFIG_DIR}/config.json"
readonly CERT_DIR="${CONFIG_DIR}/certs"
readonly SYSTEMD_DROPIN_DIR="/etc/systemd/system/sing-box.service.d"
readonly SYSTEMD_DROPIN="${SYSTEMD_DROPIN_DIR}/10-vpn-hardening.conf"
readonly JOURNAL_DROPIN_DIR="/etc/systemd/journald.conf.d"
readonly JOURNAL_DROPIN="${JOURNAL_DROPIN_DIR}/90-vpn-limits.conf"
readonly UDP_SYSCTL_FILE="/etc/sysctl.d/90-vpn-udp-buffers.conf"
readonly NFT_CONFIG="/etc/nftables.conf"
readonly SSH_DROPIN="/etc/ssh/sshd_config.d/00-vpn-hardening.conf"
readonly AUTO_FINALIZE_SSH_DROPIN="/etc/ssh/sshd_config.d/99-vpn-auto-finalize.conf"
readonly AUTO_FINALIZE_WRAPPER="/usr/local/libexec/vpn-auto-finalize-login"
readonly AUTO_FINALIZE_REMOVAL_STAGE="${STATE_DIR}/vpn-auto-finalize.conf.removing"
readonly INSTALLED_HELPER="/usr/local/sbin/vpn"
readonly USER_COMMAND="/usr/local/bin/vpn"
readonly CERT_HOOK="/etc/letsencrypt/renewal-hooks/deploy/50-vpn-sing-box"
readonly FIREWALL_UNIT_STATE="${STATE_DIR}/firewall.rollback.unit"
readonly LOG_DIR="/var/log/${PROJECT_NAME}"
readonly BOOTSTRAP_LOCK_DIR="${STATE_DIR}/install.bootstrap.lock"
readonly INSTALL_LOG_MAX_BYTES="1048576"
readonly INSTALL_LOG_RETENTION="5"
readonly -a BASE_PACKAGES=(
  apt ca-certificates curl jq openssl nftables sudo certbot dnsutils qrencode
  nginx-light unattended-upgrades openssh-client openssh-server iproute2 procps
  kmod util-linux gpg
)

ADMIN_USER=""
ADMIN_PUBLIC_KEY=""
SERVER_IPV4=""
TLS_DOMAIN=""
SSH_PORT=""
REALITY_TARGET=""
REALITY_TARGET_AUDITED=0
COUNTRY_EMOJI=""
ACME_EMAIL=""
CLIENT_FINGERPRINT=""
HY2_OBFS_MODE=""
ASSUME_YES=0
AUTOMATIC=0
VERBOSE=0
COMMAND="plan"
TMP_DIR=""
TEMP_ROOT=""
CLIENT_NAME=""
NEW_REALITY_TARGET=""
AUDIT_TARGET=""
NEW_CLIENT_FINGERPRINT=""
NEW_HY2_OBFS_MODE=""
SELF_UPDATE_SOURCE=""
OS_ID=""
OS_VERSION=""
OS_PRETTY_NAME=""
CURRENT_STEP="startup"
INSTALL_LOG_FILE=""
INSTALL_TEE_PID=""
INSTALL_LOG_ACTIVE=0
MUTATION_COMMIT_ACTIVE=0
DEFERRED_MUTATION_SIGNAL=""
DEFERRED_MUTATION_STATUS=0
ERROR_REPORTED=0
UPGRADE_ROLLBACK_ACTIVE=0
UPGRADE_ROLLBACK_FAILED=0
UPGRADE_BACKUP_DIR=""
UPGRADE_ORIGINAL_RMEM=""
UPGRADE_ORIGINAL_WMEM=""
LAST_HELPER_BACKUP=""
BOOTSTRAP_LOCK_OWNED=0
